import {videoCard} from './reviews.mjs';
// IDs refer to the preserved published Joomla menu inventory, not new routes.
export const courseGroups=[
 {id:'reiki',en:'Reiki Yggdrasil & training paths',ru:'Рейки Иггдрасиль и программы обучения',introEn:'Program structures, levels of study and introductory materials from the existing school.',introRu:'Структура программ, ступени обучения и вводные материалы школы.',ids:[213,214,222,223,228,231,252,283]},
 {id:'mysteries',en:'Mysteries & archetypal studies',ru:'Мистерии и архетипические программы',introEn:'Greek and Egyptian traditions, archetypes of love and the gods, and initiation programs.',introRu:'Традиции Греции и Египта, архетипы любви и богов, мистериальные программы и инициации.',ids:[229,254,257,258,312,314,317,320,325,326,327,332,333]},
 {id:'runes',en:'Runes, elements & symbolic practice',ru:'Руны, стихии и символические практики',introEn:'Original course descriptions on runic studies, the elements, water and symbolic objects.',introRu:'Оригинальные описания курсов по рунам, стихиям, воде и работе с символическими объектами.',ids:[227,253,256,262,264,279,315]},
 {id:'video-courses',en:'Video courses & meditations',ru:'Видеокурсы и медитации',introEn:'Recorded learning materials: solar meditations, Greek and Egyptian mysteries, planetary and Maya archetypes.',introRu:'Материалы в записи: солнечные медитации, мистерии Греции и Египта, планетарные архетипы и архетипы майя.',ids:[260,285,288,292,293,294,295,296,297,307]},
 {id:'library',en:'Books, program archives & school history',ru:'Книги, архив программ и история школы',introEn:'The wider library and earlier program outlines remain available at their original addresses.',introRu:'Библиотека и ранее опубликованные программы остаются доступны по прежним адресам.',ids:[205,211,219,220,221,268,269,275,278,284,308]}
];
export function renderAcademy(locale,catalog,e){
 const ru=locale==='ru';
 const groups=courseGroups.map(group=>{
  const items=group.ids.map(id=>catalog.find(p=>p.id===id)).filter(Boolean).sort((a,b)=>(a.language===locale?0:1)-(b.language===locale?0:1));
  return `<section class="academy-group" id="${group.id}"><h3>${e(ru?group.ru:group.en)}</h3><p>${e(ru?group.introRu:group.introEn)}</p><div class="course-list">${items.map(p=>`<a href="${e(p.url)}" class="course-link" lang="${p.language}"><span>${e(p.title)}</span><small>${p.language==='ru'?'RU':'EN'} · ${ru?'Описание программы':'Program details'} <span aria-hidden="true">↗</span></small></a>`).join('')}</div></section>`;
 }).join('');
 return `<section class="academy-catalog shell" id="programs"><p class="eyebrow">${ru?'Обучение · Библиотека':'Study · Library'}</p><h2>${ru?'Программы и курсы Академии':'Academy programs &amp; courses'}</h2><p class="section-intro">${ru?'Здесь собраны описания программ, которые были опубликованы на PsiTrends. Язык каждого материала указан рядом со ссылкой. Старые даты, цены и условия в архиве не являются действующим предложением — актуальный формат уточняйте напрямую. Исторические названия программ не означают регулируемую профессиональную квалификацию.':'Explore the program descriptions originally published on PsiTrends. Each link shows the original language. Archived dates, prices and terms are not current offers; ask directly about availability. Historical program names do not establish a regulated professional qualification.'}</p><nav class="academy-jump" aria-label="${ru?'Разделы Академии':'Academy categories'}">${courseGroups.map(g=>`<a href="#${g.id}">${e(ru?g.ru:g.en)}</a>`).join('')}</nav>${groups}<section class="academy-group" id="student-reviews"><h3>${ru?'Отзывы об обучении':'Student experiences'}</h3><p>${ru?'Сохранившиеся видеоотзывы участников курса МААТ. Личный опыт участников не является гарантией результата.':'Preserved participant videos from the MAAT course. Individual experiences are not guaranteed outcomes.'}</p><p class="small">${ru?'YouTube загружается только по нажатию.':'YouTube loads only after a click.'}</p><div class="review-grid">${['hVJr0YfLLaQ','dArVIoSKXIQ','IYXE7Lw_Bq4'].map((id,i)=>videoCard(id,`${ru?'Отзыв о курсе МААТ':'MAAT course testimonial'} ${i+1}`,ru)).join('')}</div><a class="text-link" href="https://psitrends.com/ru/cat-train-ru/advanced-ru/review-maat-ru">${ru?'Оригинальная страница отзывов':'Original course-review page'} ↗</a></section></section>`;
}
