// Reviewed masterplan and existing Toronto copy; factual gaps are omitted.
export const routes = {home:'/',hypnotherapy:'/hypnotherapy-toronto',constellations:'/systemic-constellations-toronto',about:'/about',academy:'/academy',events:'/events',contact:'/contact'};
export const shared = {
 en: {
  lang:'English', switch:'Русский', skip:'Skip to content', nav:'Main navigation', brand:'Holistic House · Andrey Litvinov',
  labels:{home:'Home',hypnotherapy:'Hypnotherapy',constellations:'Constellations',about:'About Andrey',academy:'Academy',events:'Events',contact:'Contact'},
  cta:'Ask about a session', eyebrow:'Individual sessions · Toronto & online', portrait:'Andrey Litvinov', caption:'Andrey Litvinov · Conversation, exploration, integration.',
  note:'Discuss fit, availability and fees before booking.', final:'Start with one real question.', finalText:'Tell Andrey what you would like to explore and whether you prefer Toronto or online. Keep your first message brief; avoid sending health records or sensitive personal details.',
  fallback:'Prefer another way?', telegram:'Use Telegram', phone:'Call', footer:'PsiTrends is the home of Holistic House and the Academy learning library.',
  privacy:'Your privacy', privacyText:'Contact links open WhatsApp or Telegram, where their privacy policies apply. Please share only what is needed to arrange an initial conversation.',
  analytics:'Optional analytics', analyticsText:'With your permission, Google Analytics measures visits and contact-button clicks. It does not confirm an enquiry, booking or payment. You can change your choice here.',
  allow:'Allow analytics', deny:'Keep analytics off', off:'Optional analytics is off.', on:'Optional analytics is on.', disabled:'Analytics is off on this site version.',
  processTitle:'How sessions work', processIntro:'The approach is chosen together. You do not need to use every method.',
  process:[['Map your question','Start with your goal, the situation around it and the boundaries that matter to you.'],['Explore the pattern','Notice competing needs, roles and perspectives through conversation and systemic mapping.'],['Work experientially','Discuss hypnosis, parts work or guided imagery when they fit your question.'],['Integrate','Reflect on the experience and choose a practical next step. Symbolic work is an optional addition.']],
  expectationsTitle:'A collaborative, voluntary process.',expectations:'You can ask questions, pause or decline any exercise. Experiences and outcomes vary. Discuss suitability before booking; sessions do not replace necessary medical or mental-health care.'
 },
 ru: {
  lang:'Русский',switch:'English',skip:'Перейти к содержанию',nav:'Основная навигация',brand:'Holistic House · Андрей Литвинов',
  labels:{home:'Главная',hypnotherapy:'Индивидуальная работа',constellations:'Расстановки',about:'Об Андрее',academy:'Академия',events:'События',contact:'Контакты'},
  cta:'Обсудить сессию',eyebrow:'Индивидуальные сессии · Торонто и онлайн',portrait:'Андрей Литвинов',caption:'Андрей Литвинов · Беседа, исследование, интеграция.',
  note:'До записи обсудите подход, время и стоимость.',final:'Начните с одного важного вопроса.',finalText:'Расскажите Андрею, что вы хотите исследовать, и укажите удобный формат: Торонто или онлайн. Первое сообщение может быть коротким; не отправляйте медицинские документы и другие чувствительные сведения.',
  fallback:'Удобнее другой способ?',telegram:'Написать в Telegram',phone:'Позвонить',footer:'PsiTrends объединяет индивидуальную практику Holistic House и библиотеку Академии.',
  privacy:'Конфиденциальность',privacyText:'Ссылки открывают WhatsApp или Telegram, где действуют правила конфиденциальности этих сервисов. Для первого контакта достаточно информации, необходимой, чтобы договориться о беседе.',
  analytics:'Необязательная аналитика',analyticsText:'С вашего разрешения Google Analytics измеряет посещения и нажатия на кнопки связи. Нажатие не означает заявку, запись или оплату. Вы можете изменить выбор здесь.',
  allow:'Разрешить аналитику',deny:'Оставить выключенной',off:'Необязательная аналитика выключена.',on:'Необязательная аналитика включена.',disabled:'В этой версии сайта аналитика выключена.',
  processTitle:'Как проходит сессия',processIntro:'Подход выбирается вместе. Не обязательно использовать каждый метод.',
  process:[['Обозначить вопрос','Начните с цели, обстоятельств и важных для вас границ.'],['Исследовать повторение','Заметьте разные потребности, роли и точки зрения через беседу и системное моделирование.'],['Перейти к опыту','Обсудите гипноз, работу с внутренними частями или направленное воображение, если они подходят вашему запросу.'],['Интегрировать','Осмыслите опыт и выберите практический следующий шаг. Символическая работа возможна как дополнение.']],
  expectationsTitle:'Совместная и добровольная работа.',expectations:'Вы можете задавать вопросы, делать паузу и отказаться от любого упражнения. Опыт и результаты индивидуальны. Обсудите уместность подхода до записи; сессии не заменяют необходимую медицинскую или психиатрическую помощь.'
 }
};
export const pages = {
 en: {
 home:{title:'Hypnotherapy & Constellations Toronto | Holistic House',h1:'Hypnotherapy & constellations in Toronto.',lead:'Explore repeating patterns, inner conflicts and important decisions with Andrey Litvinov.',description:'Explore individual hypnotherapy and systemic constellation sessions with Andrey Litvinov. Ask about fit, availability and meeting in Toronto or online.',introTitle:'You know the goal. Something keeps getting in the way.',intro:'A recurring relationship pattern. A difficult decision. Different parts of you pulling in different directions. Start with your experience, without needing a label for it.',serviceTitle:'Two ways to explore your question.',aboutTitle:'Work with Andrey Litvinov.',aboutText:'Conversation, systemic mapping and experiential methods come together around your question. The approach is discussed with you, rather than prescribed as a fixed sequence.',academyTitle:'A place for deeper exploration.',academyText:'The PsiTrends Academy preserves the wider library of methods, traditions, books and learning material.'},
 hypnotherapy:{title:'Hypnotherapy Toronto | Andrey Litvinov · Holistic House',h1:'Hypnotherapy in Toronto.',lead:'A guided, collaborative way to explore patterns, goals and inner responses.',description:'Explore individual hypnotherapy sessions in Toronto or online. Learn how sessions work and ask Andrey Litvinov about suitability, availability and fees.',introTitle:'Start with one real situation.',intro:'You may understand what you want and still find yourself hesitating, overthinking or repeating a familiar response. A session offers space to explore that experience through conversation, focused attention and imagery.',detailTitle:'What hypnosis means here.',detail:'Guided attention and imagination can help you explore your own responses. Systemic mapping or work with inner parts may also be discussed. You remain a participant: ask questions and choose whether to continue.',faq:[['Will I have a say in the process?','Yes. Discuss the approach before starting, ask questions and choose whether to participate. You can ask to pause or stop at any time.'],['How many sessions will I need?','There is no promised number of sessions or guaranteed result. Start by discussing your question and whether this approach is a suitable fit.'],['Can we meet online?','Mention your preferred format in your enquiry. Confirm availability, duration and fees with Andrey before booking.']]},
 constellations:{title:'Systemic & Family Constellations Toronto | Holistic House',h1:'Systemic & family constellations in Toronto.',lead:'Make room for another perspective on relationships, roles and important decisions.',description:'Explore relationship patterns, roles and important decisions with Andrey Litvinov. Ask about an individual constellation session in Toronto or online.',introTitle:'Look at the relationships around a question.',intro:'A constellation is an experiential way to map a situation. Positions, objects or representations can help you explore how you perceive relationships, roles and competing needs.',detailTitle:'Your experience is the starting point.',detail:'Individual work focuses on your perspective. Observations are starting points for reflection, not proof about other people or your family history. You do not need to bring your family to explore a relationship question.',businessTitle:'A space for a business or decision question.',business:'Map roles, competing priorities and possible perspectives around a decision. Use the session as reflection alongside practical research and professional advice. It is not financial or legal advice, and business outcomes are not guaranteed.',faq:[['Is this individual or group work?','This page introduces individual constellation work. Ask about the format that is currently available before booking.'],['Does an exercise reveal facts about my family?','No. A representation or feeling does not establish a factual truth about absent people or family history.'],['What can I bring to a session?','A relationship pattern, a difficult decision, a role that feels uncomfortable or competing priorities. Begin with your own perspective.']]},
 about:{title:'About Andrey Litvinov | Holistic House · PsiTrends',h1:'Andrey Litvinov.',lead:'Individual work shaped around your question, with room for conversation and experience.',description:'Meet Andrey Litvinov and explore his approach to individual sessions, systemic mapping and the PsiTrends knowledge library.',introTitle:'A question comes before a method.',intro:'The work brings together conversation, systemic mapping, hypnosis, inner-parts exploration and guided imagery where appropriate. Discuss what you want to explore and agree on the approach together.',detailTitle:'Practice and learning, connected.',detail:'Holistic House is the individual-practice identity within PsiTrends. The Academy holds the wider library of educational and historical material. Exploring the library is optional; you do not need to learn a whole system before asking about a session.',supportTitle:'Supporting methods are optional.',support:'Reiki and symbolic mandala or artifact work are options to discuss when relevant. They are not requirements for a session or promises of a particular outcome.'},
 contact:{title:'Contact Andrey Litvinov | Holistic House · PsiTrends',h1:'Ask about a session.',lead:'A short conversation is the first step. Tell Andrey what you would like to explore.',description:'Ask about an individual session with Andrey Litvinov, meeting format, availability and fees. Contact via WhatsApp or Telegram.',introTitle:'What to include in your message.',intro:'Mention the type of session you are considering, your preference for Toronto or online, and a good way to reply. A brief, general description is enough.',detailTitle:'Agree the practical details together.',detail:'Before booking, discuss suitability, format, availability, duration and fees. Please avoid sending sensitive health details or medical records in your first message.'},
 academy:{title:'PsiTrends Academy | Methods, Books & Learning Library',h1:'PsiTrends Academy.',lead:'A library for deeper exploration: systemic work, archetypes, traditions and symbolic methods.',description:'Explore the PsiTrends library of systemic work, archetypes, traditions, symbolic methods, books, videos and historical programs.',introTitle:'Follow your curiosity.',intro:'This library brings together educational material and historical programs. An archive page does not establish that a program is currently available. Ask about availability before making plans.',libraryTitle:'Explore the existing library.',detailTitle:'Looking for an individual session?',detail:'You can come directly to the client practice. You do not need to work through the library first.',links:[['Books','Reading and reference material.','/studies/books'],['Traditions & mysteries','The historical methods archive.','/mysteries'],['Reiki traditions','An existing learning archive.','/studies/adv/reiki'],['Mandalas & artifacts','Symbolic methods and materials.','/mandalas-and-artifacts'],['Videos · Russian','The Russian-language video library.','/ru/video-kursy'],['Academy background','The historical Academy About page.','/studies/about-us']]},
 events:{title:'Events Archive | Andrii Litvinov · PsiTrends',h1:'Events Archive',lead:'Workshops, retreats & group practice',description:'Archive of workshops, retreats, constellations, mystery practices and group programs facilitated by Andrii Litvinov since 2006.',introTitle:'Documented group-work history.',intro:'A visual archive of documented workshops, retreats and group practice from 2006 onward.'}
 },
 ru: {
 home:{title:'Индивидуальная работа и расстановки | Holistic House',h1:'Индивидуальная работа и системные расстановки.',lead:'Исследуйте повторяющиеся сценарии, внутренние противоречия и важные решения вместе с Андреем Литвиновым.',description:'Индивидуальные сессии гипноза и системных расстановок с Андреем Литвиновым. Обсудите подходящий формат, время и стоимость: Торонто или онлайн.',introTitle:'Цель понятна. Но что-то мешает двигаться.',intro:'Повторяющийся сценарий в отношениях. Сложное решение. Разные части вас хотят разного. Начните со своего опыта — для него не обязательно подбирать готовое определение.',serviceTitle:'Два подхода к вашему вопросу.',aboutTitle:'Работа с Андреем Литвиновым.',aboutText:'Беседа, системное моделирование и работа с опытом объединяются вокруг вашего запроса. Подход обсуждается с вами, а не задаётся одной схемой для всех.',academyTitle:'Пространство для углублённого изучения.',academyText:'Академия PsiTrends сохраняет библиотеку методов, традиций, книг и учебных материалов.'},
 hypnotherapy:{title:'Гипноз и индивидуальная работа | Андрей Литвинов',h1:'Гипноз и индивидуальная работа.',lead:'Совместное исследование повторяющихся реакций, целей и внутреннего опыта.',description:'Индивидуальная работа с Андреем Литвиновым в Торонто или онлайн. Узнайте о формате сессии и обсудите подход, время и стоимость.',introTitle:'Начните с конкретной ситуации.',intro:'Можно понимать свою цель и всё же откладывать решение, сомневаться или возвращаться к привычной реакции. Сессия даёт пространство для исследования этого опыта через беседу, сосредоточенное внимание и образы.',detailTitle:'Что здесь означает гипноз.',detail:'Направленное внимание и воображение помогают исследовать собственные реакции. При необходимости можно обсудить системное моделирование или работу с внутренними частями. Вы участвуете в выборе подхода и можете остановиться.',faq:[['Могу ли я влиять на ход сессии?','Да. Обсудите подход до начала, задавайте вопросы и решайте, хотите ли участвовать в упражнении. В любой момент можно сделать паузу или остановиться.'],['Сколько сессий потребуется?','Фиксированное число сессий и определённый результат не обещаются. Начните с обсуждения запроса и того, подходит ли вам такой формат.'],['Возможна ли работа онлайн?','Укажите желаемый формат в первом сообщении. До записи уточните у Андрея доступное время, длительность и стоимость.']]},
 constellations:{title:'Системные и семейные расстановки | Андрей Литвинов',h1:'Системные и семейные расстановки.',lead:'Другой взгляд на отношения, роли и важные решения.',description:'Исследуйте отношения, роли и важные решения с Андреем Литвиновым. Обсудите индивидуальную расстановку в Торонто или онлайн.',introTitle:'Посмотрите на связи вокруг вашего вопроса.',intro:'Расстановка — способ исследовать ситуацию через опыт. Позиции, предметы и образы помогают рассмотреть, как вы воспринимаете отношения, роли и разные потребности.',detailTitle:'Отправная точка — ваш опыт.',detail:'Индивидуальная работа сосредоточена на вашей точке зрения. Наблюдения дают материал для размышления, но не доказывают факты о других людях или истории семьи. Для исследования отношений не обязательно приглашать родственников.',businessTitle:'Вопросы бизнеса и важных решений.',business:'Рассмотрите роли, разные приоритеты и возможные точки зрения. Используйте сессию для размышления наряду с практическим исследованием и профессиональной консультацией. Это не финансовая или юридическая рекомендация; коммерческий результат не гарантируется.',faq:[['Это индивидуальная или групповая работа?','На этой странице представлен индивидуальный формат. Перед записью уточните, какие форматы доступны сейчас.'],['Расстановка раскрывает факты о моей семье?','Нет. Образ или ощущение не устанавливает фактическую истину об отсутствующих людях или семейной истории.'],['С каким вопросом можно прийти?','Повторение в отношениях, сложное решение, неудобная роль или противоречащие друг другу приоритеты. Начните с собственной точки зрения.']]},
 about:{title:'Об Андрее Литвинове | Holistic House · PsiTrends',h1:'Андрей Литвинов.',lead:'Индивидуальная работа вокруг вашего запроса — через беседу и исследование опыта.',description:'Подход Андрея Литвинова к индивидуальным сессиям, системному моделированию и библиотеке знаний PsiTrends.',introTitle:'Сначала вопрос, потом метод.',intro:'В работе могут сочетаться беседа, системное моделирование, гипноз, исследование внутренних частей и направленное воображение. Сначала обсудите, что хотите исследовать, и вместе выберите подход.',detailTitle:'Практика и обучение рядом.',detail:'Holistic House — индивидуальная практика внутри PsiTrends. Академия сохраняет более широкую библиотеку учебных и исторических материалов. Чтобы обсудить сессию, не нужно предварительно изучать всю систему.',supportTitle:'Дополнительные методы — по желанию.',support:'Рейки и символическая работа с мандалами или артефактами могут обсуждаться, если они уместны. Они не являются обязательной частью сессии и не обещают определённого результата.'},
 contact:{title:'Связаться с Андреем Литвиновым | Holistic House',h1:'Обсудить индивидуальную сессию.',lead:'Первый шаг — короткая беседа. Расскажите, что вы хотите исследовать.',description:'Обсудите с Андреем Литвиновым индивидуальную сессию, формат, доступное время и стоимость через WhatsApp или Telegram.',introTitle:'Что написать в первом сообщении.',intro:'Укажите интересующий вас тип сессии, удобный формат — Торонто или онлайн — и способ связи. Достаточно короткого общего описания.',detailTitle:'Практические детали обсудим вместе.',detail:'До записи уточните уместность подхода, формат, доступное время, длительность и стоимость. Не отправляйте медицинские документы и чувствительные сведения в первом сообщении.'},
 academy:{title:'Академия PsiTrends | Методы, книги и библиотека',h1:'Академия PsiTrends.',lead:'Библиотека для углублённого изучения: системная работа, архетипы, традиции и символические методы.',description:'Библиотека PsiTrends: системная работа, архетипы, традиции, символические методы, книги, видео и исторические программы.',introTitle:'Следуйте своему интересу.',intro:'Библиотека объединяет учебные материалы и исторические программы. Страница в архиве не означает, что программа доступна сейчас. Уточняйте актуальность перед тем, как строить планы.',libraryTitle:'Откройте существующую библиотеку.',detailTitle:'Ищете индивидуальную сессию?',detail:'Можно сразу обратиться к индивидуальной практике. Для этого не нужно сначала изучать материалы библиотеки.',links:[['Видеоматериалы','Библиотека видео и учебных программ.','/ru/video-kursy'],['Мандалы и артефакты','Символические методы и материалы.','/ru/mandaly-i-artefakty'],['Архетипы майя','Материалы существующей видеобиблиотеки.','/ru/video-kursy/arkhetipy-majya'],['История Академии','Историческая страница об Академии.','/ru/cat-train-ru/about-us-ru'],['Книги · English','Раздел книг на английском языке.','/studies/books'],['Традиции · English','Архив материалов на английском языке.','/mysteries']]},
 events:{title:'Архив мероприятий | Андрей Литвинов · PsiTrends',h1:'Архив мероприятий',lead:'Мастерские, ретриты и групповая практика',description:'Архив мастерских, семинаров, расстановок, мистериальных практик и групповых программ Андрея Литвинова с 2006 года.',introTitle:'Документальная история групповой работы.',intro:'Визуальный архив документально подтверждённых мастерских, ретритов и групповой практики с 2006 года.'}
 }
};

export const authorProfiles = {
 en: {
  hero:{h1:'Let me introduce myself.',intro:['I’m Andy, a Jungian-oriented specialist and facilitator of archetypal practices.','Raised in Ukraine but living for 20 years worldwide.']},
  experienceTitle:'Experience',
  experience:[
   '24 years of facilitating group and personal growth programs, since 2002.',
   '22 years of experience facilitating transpersonal temple-based practices since 2004. Master Teacher of Tantra Reiki, Kundalini Reiki, and Runic Reiki.',
   '15 years of experience facilitating Family and Business Constellations, since 2011.'
  ],
  studiesTitle:'Specializations / studies',
  studies:[
   ['Dreams Alive / Guided Imagery Work','Exploring tensions and Inner Child experiences through imagery and unconscious material.'],
   ['Body-oriented Work','Exploring early developmental and Inner Child patterns through body awareness and conscious, consent-based touch.'],
   ['Archetypal Temple Work','Exploring personal and business goals through systemic constellations and temple archetypes.'],
   ['Taoist Alchemy','Exploring mind-body experiences through traditional energetic and symbolic models, including my educational framework of Psychic Homeopathy.']
  ],
  tantricTitle:'Tantric workshops',
  tantricIntro:'I did tantric workshops since 2004 in different schools and traditions worldwide, for 20 years. But the most fascinating and transformative for me, I would say, was the ISTA school approach.',
  psychotherapy:[
   'Though my primary interest is depth-oriented personal work.',
   'A central part of my studies has been Guided Affective Imagery (Hanscarl Leuner).',
   'This approach creates a bridge between Jungian depth traditions and Freudian psychoanalytic approaches.'
  ],
  bodywork:{intro:'As for bodywork, my studies were influenced by',schools:['European body-oriented approaches','the Bodynamic Analysis approach']},
  narrative:[
   'These approaches explore connections between early developmental experiences and patterns held in the body.',
   'But I would say one of the biggest influences for me was the Temple Studies. Initiations into the Greek Temple Mysteries. Mysteries of Dionysus, Demeter, etc. Egyptian Temple magic and mysteries.',
   'That is the experience that not only gives you the knowledge, but the sense of the field, archetypes, transpersonal flow.',
   'That I was studying and teaching worldwide for 20 years.',
   'A starting point for learning to feel this flow for me was a series of Reiki initiations, including Tantra Reiki, a lineage described within its tradition as connected to Osho-inspired teachings.'
  ],
  reviewsTitle:'Testimonials', reviewsNote:'Public review images already shared on the PsiTrends home page.',
  exploreTitle:'Explore my work', explore:{sessions:'Individual Sessions',workshops:'Workshops',academy:'Studies / Academy',contact:'Contact'},
  reviews:['IMG_20241121_193918_816.jpg','IMG_20241121_193919_060.jpg','IMG_20241121_193919_048.jpg','IMG_20241121_193919_103.jpg']
 },
 ru: {
  hero:{h1:'Позвольте представиться.',intro:['Я Энди, джунгиански ориентированный специалист и ведущий архетипических практик.','Я вырос в Украине, но уже 20 лет живу в разных странах мира.']},
  experienceTitle:'Опыт',
  experience:[
   '24 года веду групповые и программы личностного роста — с 2002 года.',
   '22 года веду трансперсональные храмовые практики — с 2004 года. Master Teacher Tantra Reiki, Kundalini Reiki и Runic Reiki.',
   '15 лет веду семейные и бизнес-расстановки — с 2011 года.'
  ],
  studiesTitle:'Специализации / обучение',
  studies:[
   ['Dreams Alive / работа с направленными образами','Исследование внутренних напряжений и опыта внутреннего ребёнка через образы и бессознательный материал.'],
   ['Телесно-ориентированная работа','Исследование ранних паттернов развития и опыта внутреннего ребёнка через осознавание тела и осознанное прикосновение с согласия.'],
   ['Архетипическая храмовая работа','Исследование личных и бизнес-целей через системные расстановки и храмовые архетипы.'],
   ['Даосская алхимия','Исследование связи внутреннего опыта и телесных ощущений через традиционные энергетические и символические модели, включая мою образовательную концепцию Psychic Homeopathy.']
  ],
  tantricTitle:'Тантрические семинары',
  tantricIntro:'С 2004 года я веду тантрические семинары в разных школах и традициях по всему миру — уже 20 лет. Но самым увлекательным и трансформирующим для меня, я бы сказал, стал подход школы ISTA.',
  psychotherapy:[
   'При этом мой главный интерес — глубинная личная работа.',
   'Одна из центральных частей моего обучения — Guided Affective Imagery (Hanscarl Leuner).',
   'Этот подход создаёт мост между юнгианской глубинной традицией и фрейдистскими психоаналитическими подходами.'
  ],
  bodywork:{intro:'Что касается телесной работы, на моё обучение повлияли',schools:['европейские телесно-ориентированные подходы','подход Bodynamic Analysis']},
  narrative:[
   'Эти подходы исследуют связи между ранним опытом развития и телесными паттернами.',
   'Но одним из самых больших влияний для меня стали Temple Studies. Посвящения в греческие храмовые мистерии. Мистерии Диониса, Деметры и другие. Египетская храмовая магия и мистерии.',
   'Этот опыт даёт не только знание, но и ощущение поля, архетипов, трансперсонального потока.',
   'Его я изучал и преподавал по всему миру 20 лет.',
   'А одной из отправных точек для ощущения этого потока стали серии посвящений Рейки, включая Tantra Reiki — направление, которое внутри этой традиции описывают как связанное с идеями Ошо.'
  ],
  reviewsTitle:'Отзывы', reviewsNote:'Публичные изображения отзывов, уже размещённые на главной странице PsiTrends.',
  exploreTitle:'Исследуйте мою работу', explore:{sessions:'Индивидуальные сессии',workshops:'Воркшопы',academy:'Обучение / Академия',contact:'Связаться'},
  reviews:['IMG_20241121_193918_816.jpg','IMG_20241121_193919_060.jpg','IMG_20241121_193919_048.jpg','IMG_20241121_193919_103.jpg']
 }
};
