// Original published testimonial sections: Quix page 4 (EN), page 141 (RU).
// Preserve source media, without inventing names, quotes or outcome claims.
export const reviews={
 en:{source:4,photos:['photo_2023-05-07_00-12-29.jpg','photo_2023-06-10_01-35-08.jpg','photo_2023-06-10_01-37-38.jpg','photo_2023-06-10_01-37-44.jpg','otzuvu/IMG_20241121_193918_816.jpg','otzuvu/IMG_20241121_193919_060.jpg','otzuvu/IMG_20241121_193919_048.jpg','otzuvu/IMG_20241121_193919_103.jpg'],videos:['Dk0LBmOivQo','1DQF5C3fX9M','OrdMvKn2Zg8','aUJde6A-9p0','fE6sD1zr1Js','itjo2_z2NGk','8dz_mJ-KkEc']},
 ru:{source:141,photos:['photo_2023-06-04_21-44-02.jpg','photo_2023-06-04_21-43-48.jpg','photo_2023-05-30_03-18-24.jpg','photo_2023-05-05_06-46-22.jpg','photo_2023-06-06_07-58-46.jpg'],videos:['ttQxUHopaUM','VABgpmn4ZYA','muOnIHllI7E','tmUqLa_Lj3E','MIVLm1GUTtM','LhY_5aUYI2s','KNtBougn3gw']}
};
export function videoCard(id,label,ru){
 const externalOnly=id==='OrdMvKn2Zg8'; // Existing video returns oEmbed 403: retain source without a broken embedded player.
 return `<article class="review-video"><div class="video-stage"><a class="video-load"${externalOnly?'':` data-video="${id}"`} href="https://www.youtube.com/watch?v=${id}" target="_blank" rel="noopener noreferrer"><span class="play-symbol" aria-hidden="true">▶</span><span>${label}</span><small>${externalOnly?(ru?'Оригинал на YouTube · встраивание недоступно':'YouTube original · embedding unavailable'):(ru?'Загрузить видео':'Load video')}</small></a></div><a class="video-original" href="https://www.youtube.com/watch?v=${id}" target="_blank" rel="noopener noreferrer">${ru?'Открыть на YouTube':'Open on YouTube'} <span class="link-arrow" aria-hidden="true"></span></a></article>`;
}
export function renderReviews(locale,{source=false}={}){
 const ru=locale==='ru',c=reviews[locale];
 const photos=c.photos.map((file,i)=>{const url=`${source?'https://psitrends.com':''}/images/${file}`;return `<a class="review-photo" href="${url}" target="_blank" rel="noopener noreferrer"><img src="${url}" loading="lazy" width="480" height="360" alt="${ru?'Ранее опубликованный отзыв, изображение':'Previously published review image'} ${i+1}"><span>${ru?'Открыть отзыв':'Read original review'} ${i+1} <span class="link-arrow" aria-hidden="true"></span></span></a>`;});
 const videos=c.videos.map((id,i)=>videoCard(id,`${ru?'Видеоотзыв':'Video testimonial'} ${i+1}`,ru));
 const gallery=(items,label)=>`<div class="review-grid">${items.slice(0,3).join('')}</div>${items.length>3?`<details class="review-more"><summary>${label} (${items.length-3})</summary><div class="review-grid">${items.slice(3).join('')}</div></details>`:''}`;
 return `<section class="reviews-section shell" id="reviews" aria-labelledby="reviews-title"><p class="eyebrow">${ru?'Личный опыт':'Personal experiences'}</p><h2 id="reviews-title">${ru?'Отзывы и истории участников':'Reviews &amp; participant stories'}</h2><p class="section-intro">${ru?'Фото- и видеоотзывы, ранее опубликованные на PsiTrends. Сохраняем оригиналы и слова их авторов. Это индивидуальный опыт, а не обещание результата или медицинская рекомендация.':'Photo and video testimonials previously published on PsiTrends, preserved in their original form. These are individual experiences, not promised outcomes or medical advice.'}</p><h3>${ru?'Отзывы в фотографиях':'Photo testimonials'}</h3>${gallery(photos,ru?'Ещё фотоотзывы':'More photo testimonials')}<h3 class="video-heading">${ru?'Видеоотзывы':'Video testimonials'}</h3><p class="small">${ru?'YouTube подключается только после нажатия «Загрузить видео». Можно также открыть оригинал в новой вкладке.':'YouTube connects only when you choose Load video. You can also open the original in a new tab.'}</p>${gallery(videos,ru?'Ещё видеоотзывы':'More video testimonials')}</section>`;
}
