import {authorProfiles,pages,shared,routes} from './content.mjs';
import {home,renderHome} from './home.mjs';
import {renderReviews} from './reviews.mjs';
import {renderAcademy} from './academy.mjs';
import {renderEvents} from './events.mjs';
import catalog from './academy-catalog.json' with {type:'json'};
export const sourceName=(key,locale)=>`psitrends-client-${key}${locale==='ru'?'-ru':''}`;
export const routeFor=(key,locale)=>locale==='ru'?`/ru${routes[key]}`:routes[key];
const esc=x=>String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export function render(key,locale,{source=false,production=false}={}){
 const c=key==='home'?{...pages[locale][key],...home[locale]}:pages[locale][key],s={...shared[locale],final:home[locale].final,finalText:home[locale].finalText},other=locale==='en'?'ru':'en',link=(k,l=locale)=>source?`${sourceName(k,l)}.html`:routeFor(k,l),asset=x=>source?`integrations/psitrends-client/${x}`:`/psitrends-client-assets/${x}`;
 const portraitName=['home','about'].includes(key)?'andy-library-desk.png':'andrey.jpg',portrait=asset(portraitName),dims=portraitName==='andy-library-desk.png'?{width:1079,height:1057}:{width:1075,height:1265},reviewAsset=source?'integrations/psitrends-client/reviews/':'/psitrends-client-assets/reviews/',css=source?`${sourceName(key,locale)}.css?v=5`:'/psitrends-client-assets/psitrends-client.css?v=5',js=source?'psitrends-client.js?v=5':'/psitrends-client-assets/psitrends-client.js?v=5',arrow='<span class="link-arrow" aria-hidden="true"></span>',canonical=`https://psitrends.com${routeFor(key,locale)}`;
 const message=locale==='ru'?'Здравствуйте, Андрей! Хочу обсудить индивидуальную сессию.':'Hi Andrey, I would like to ask about an individual session.',cta=()=>`<a class="button" data-contact="whatsapp" href="https://wa.me/14376066502?text=${encodeURIComponent(message)}">${esc(s.cta)} ${arrow}</a>`;
 const services=()=>`<div class="service-links">${['hypnotherapy','constellations'].map(k=>`<a class="service-link" href="${link(k)}"><span>${esc(s.labels[k])}</span>${arrow}</a>`).join('')}</div>`;
 const profile=authorProfiles[locale],reviews=profile.reviews.map((x,i)=>`<a class="author-review" href="${reviewAsset}${x}" target="_blank" rel="noopener noreferrer"><img src="${reviewAsset}${x}" loading="lazy" width="480" height="360" alt="${esc(`${profile.reviewsTitle} ${i+1}`)}"><span>${esc(profile.reviewsTitle)} ${i+1} ${arrow}</span></a>`).join('');
 const author=()=>`<section class="author-profile shell" id="explore"><article class="reading-column"><section class="profile-chapter"><h2>${esc(profile.experienceTitle)}</h2><ol class="profile-list profile-experience">${profile.experience.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></section><section class="profile-chapter"><h2>${esc(profile.studiesTitle)}</h2><ol class="profile-list profile-studies">${profile.studies.map(([a,b])=>`<li><h3>${esc(a)}</h3><p>${esc(b)}</p></li>`).join('')}</ol></section><section class="profile-chapter"><h2>${esc(profile.tantricTitle)}</h2><p>${esc(profile.tantricIntro)}</p>${profile.psychotherapy.map(x=>`<p>${esc(x)}</p>`).join('')}<p>${esc(profile.bodywork.intro)}</p><ul class="profile-bodywork">${profile.bodywork.schools.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${profile.narrative.map(x=>`<p>${esc(x)}</p>`).join('')}</section></article></section><section class="author-reviews shell"><div class="author-reviews-heading"><p class="eyebrow">PsiTrends</p><h2>${esc(profile.reviewsTitle)}</h2><p>${esc(profile.reviewsNote)}</p></div><div class="author-reviews-grid">${reviews}</div></section><section class="author-explore shell"><div><p class="eyebrow">PsiTrends</p><h2>${esc(profile.exploreTitle)}</h2></div><nav class="author-explore-links"><a href="${link('hypnotherapy')}">${esc(profile.explore.sessions)} ${arrow}</a><a href="#contact">${esc(profile.explore.workshops)} ${arrow}</a><a href="${link('academy')}">${esc(profile.explore.academy)} ${arrow}</a></nav>${cta()}</section>`;
 let body=key==='about'?author():key==='events'?renderEvents(locale,{asset,escape:esc}):`<section class="section shell" id="explore"><div class="section-heading"><h2>${esc(c.introTitle)}</h2></div><div class="section-copy"><p>${esc(c.intro)}</p></div></section>`;
 if(key==='home')body=renderHome(locale,{link,cta,assets:{portrait,atmosphere:asset('archway.webp'),heritage:source?'output/psitrends-local-copy-assets/photo_2023-01-27_06-22-45.jpg':'/images/photo_2023-01-27_06-22-45.jpg'},escape:esc,services})+renderReviews(locale,{source});
 if(key==='academy')body=renderAcademy(locale,catalog,esc,{source})+body;
 const hero=key==='about'?profile.hero:c,nav=[['consultations',locale==='en'?'Consultations':'Консультации'],['training',locale==='en'?'Training':'Обучение'],['workshops',locale==='en'?'Workshops':'Семинары']];
 return `<!doctype html><html lang="${locale}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>${esc(c.title)}</title><meta name="description" content="${esc(c.description)}"><meta name="robots" content="${production?'index, follow':'noindex, nofollow'}">${production?`<link rel="canonical" href="${canonical}"><link rel="alternate" hreflang="en-GB" href="https://psitrends.com${routeFor(key,'en')}"><link rel="alternate" hreflang="ru-RU" href="https://psitrends.com${routeFor(key,'ru')}">`:''}<link rel="stylesheet" href="${css}"><script src="${js}" defer></script></head><body data-analytics-mode="${production?'consent':'off'}" data-page="${key}" data-locale="${locale}"><a class="skip-link" href="#main">${esc(s.skip)}</a><header class="site-header"><div class="shell header-top"><a class="brand" href="${link('home')}">PsiTrends<span>Holistic House</span></a><nav class="nav" id="primary-nav" aria-label="${esc(s.nav)}">${nav.map(([id,label])=>`<a href="${key==='home'?'':link('home')}#${id}">${label}</a>`).join('')}${['about','events','contact'].map(k=>`<a href="${link(k)}"${k===key?' aria-current="page"':''}>${locale==='en'&&k==='about'?'About':esc(s.labels[k])}</a>`).join('')}</nav><a class="language" href="${link(key,other)}" lang="${other}" hreflang="${other}">${other.toUpperCase()}</a></div></header><main id="main">${key==='events'?'':`<section class="hero"><div class="shell hero-layout"><div class="hero-copy"><p class="eyebrow">${key==='about'?(locale==='en'?'Author profile':'Авторский профиль'):esc(s.eyebrow)}</p><h1>${esc(hero.h1)}</h1>${key==='about'?hero.intro.map(x=>`<p class="lead">${esc(x)}</p>`).join(''):`<p class="lead">${esc(hero.lead)}</p><div class="hero-actions">${cta()}</div>`}</div><figure class="${key==='home'?'hero-portrait':'portrait'}"><img src="${key==='about'||key==='home'?portrait:asset('archway.webp')}" width="${key==='about'||key==='home'?dims.width:1536}" height="${key==='about'||key==='home'?dims.height:1024}" alt="${esc(s.portrait)}" fetchpriority="high"></figure></div></section>`}${body}<section class="contact-band" id="contact"><div class="shell contact-layout"><div><h2>${esc(s.final)}</h2><p>${esc(s.finalText)}</p></div><div class="contact-actions">${cta()}</div></div></section></main><footer class="shell footer"><p>PsiTrends · Holistic House</p><details id="analytics-choice"><summary>${esc(s.analytics)}</summary><button type="button" data-analytics="allow">${esc(s.allow)}</button><button type="button" data-analytics="deny">${esc(s.deny)}</button></details></footer></body></html>`;
}
